[package]
name = "newpub-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
newpub-core.workspace = true
newpub-engine.workspace = true
eframe.workspace = true
egui.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "=0.61.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Printing",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Storage_Xps",
] }
