//! Agent access (AG-01, AG-02): everything a person can do in newpub, for an AI agent.
//!
//! The engine already speaks JSON: every user action is an [`Action`] and every question a [`Query`]
//! (ARCHITECTURE.md §4). This crate puts an MCP server (Model Context Protocol, JSON-RPC 2.0 over stdio)
//! and a command line in front of that interface, so an agent can open, build, inspect, render, check,
//! save and export publications with the same vocabulary the journeys use. The desktop app can host the
//! same server (`newpub --agent`), so a person watches the agent work on the open publication.
//!
//! The tool dispatch is generic over a [`Host`]: the headless server uses a bare `Session`, the app
//! implements `Host` on itself to keep its view in step.

use std::io::{BufRead, Write};
use std::sync::{Arc, Mutex, mpsc};

use anyhow::{Result, anyhow, bail};
use base64::Engine as _;
use newpub_core::{Id, ObjectKind};
use newpub_engine::{Action, Query, Session, SessionAction};
use serde_json::{Map, Value, json};

/// The action and query reference, generated by `tools/agent/reference.py` from the Rust sources.
pub const REFERENCE: &str = include_str!("../../../docs/agent-reference.md");
/// Server name and version reported to MCP clients.
pub const SERVER_NAME: &str = "newpub";
pub const SERVER_VERSION: &str = env!("CARGO_PKG_VERSION");
/// MCP protocol revisions this server speaks; the first is the default.
pub const PROTOCOL_VERSIONS: &[&str] = &["2025-06-18", "2025-03-26", "2024-11-05"];
/// URI of the reference resource.
pub const REFERENCE_URI: &str = "newpub://reference";
/// Highest resolution `newpub_render_page` renders at.
const MAX_DPI: f64 = 300.0;

/// What the tools act on: the headless server's session, or the running app.
pub trait Host {
    fn session(&mut self) -> &mut Session;
    /// Called after a tool ran one or more actions, with a one-line summary (the app shows it in its status bar
    /// and brings its view in step with the document).
    fn after_actions(&mut self, _summary: &str) {}
}

impl Host for Session {
    fn session(&mut self) -> &mut Session {
        self
    }
}

/// Result of a tool call, as MCP reports it.
#[derive(Clone, Debug, Default)]
pub struct ToolResult {
    /// Content blocks (`{type: "text", text}` or `{type: "image", data, mimeType}`).
    pub content: Vec<Value>,
    /// Machine-readable result, when the tool has one.
    pub structured: Option<Value>,
    pub is_error: bool,
}

impl ToolResult {
    fn text(s: impl Into<String>) -> ToolResult {
        ToolResult { content: vec![json!({"type": "text", "text": s.into()})], structured: None, is_error: false }
    }

    fn data(summary: impl Into<String>, value: Value) -> ToolResult {
        let text = format!("{}\n{}", summary.into(), pretty(&value));
        ToolResult { content: vec![json!({"type": "text", "text": text})], structured: Some(value), is_error: false }
    }

    fn error(e: impl std::fmt::Display) -> ToolResult {
        ToolResult { content: vec![json!({"type": "text", "text": e.to_string()})], structured: None, is_error: true }
    }

    /// The MCP `tools/call` result object.
    pub fn to_json(&self) -> Value {
        let mut v = json!({"content": self.content, "isError": self.is_error});
        if let Some(s) = &self.structured {
            v["structuredContent"] = s.clone();
        }
        v
    }
}

fn pretty(v: &Value) -> String {
    serde_json::to_string_pretty(v).unwrap_or_else(|_| v.to_string())
}

// ---- Tools ------------------------------------------------------------------------------------------------

/// The tool list for `tools/list`.
pub fn tools() -> Vec<Value> {
    let obj = |props: Value, required: &[&str]| json!({"type": "object", "properties": props, "required": required, "additionalProperties": false});
    vec![
        json!({
            "name": "newpub_reference",
            "description": "The vocabulary of newpub_action and newpub_query: every action (document commands and \
                session actions) and every query with its fields. Call it with `search` for the entries whose name \
                or description mention a word (e.g. \"link\", \"table\", \"export\"), with `names_only` for the bare \
                list, or with nothing for the whole reference (about 28 KB).",
            "inputSchema": obj(json!({
                "search": {"type": "string", "description": "Case-insensitive word or phrase to look for."},
                "names_only": {"type": "boolean", "description": "Return only the action and query names."}
            }), &[]),
        }),
        json!({
            "name": "newpub_status",
            "description": "Where things stand: the file, unsaved changes, page size, every page with its objects \
                (id, kind, name, rect, text preview, overflow), undo availability, and warnings such as overflowing \
                stories and missing fonts. Call it first, and after a batch of changes.",
            "inputSchema": obj(json!({}), &[]),
        }),
        json!({
            "name": "newpub_action",
            "description": "Run one action: a document command or a session action by name (see newpub_reference), \
                e.g. action \"add_text_frame\" with args {\"page\": 0, \"rect\": {\"x\": 72, \"y\": 72, \"w\": 300, \
                \"h\": 200}}. Lengths may be numbers of points or strings with units (\"2in\", \"50mm\"). Returns \
                the ids it created. Every action is one undo step (\"undo\" and \"redo\" are actions too).",
            "inputSchema": obj(json!({
                "action": {"type": "string", "description": "The action name (the `cmd` tag)."},
                "args": {"type": "object", "description": "The action's fields."}
            }), &["action"]),
        }),
        json!({
            "name": "newpub_actions",
            "description": "Run several actions in order as ONE undo step (an undo group), stopping at the first \
                failure. Each item is {\"action\": name, \"args\": {...}}. Use it for a whole edit such as \"add a \
                frame, put text in it, format it\".",
            "inputSchema": obj(json!({
                "actions": {"type": "array", "items": {"type": "object", "properties": {
                    "action": {"type": "string"}, "args": {"type": "object"}}, "required": ["action"]}},
                "undo_group": {"type": "boolean", "description": "Group into one undo step (default true)."}
            }), &["actions"]),
        }),
        json!({
            "name": "newpub_query",
            "description": "Ask a read-only question by name (see newpub_reference), e.g. query \"story_text\" with \
                args {\"target\": 12}, \"frame_lines\" for measured line positions, \"overflow\", \"page_objects\", \
                \"document\" for the whole model, \"accessibility_check\", \"find\". Returns JSON.",
            "inputSchema": obj(json!({
                "query": {"type": "string", "description": "The query name (the `q` tag)."},
                "args": {"type": "object", "description": "The query's fields."}
            }), &["query"]),
        }),
        json!({
            "name": "newpub_render_page",
            "description": "Render a page to a PNG image so you can look at it. `page` is 0-based; `dpi` defaults to \
                72 (one point per pixel) and may go up to 300.",
            "inputSchema": obj(json!({
                "page": {"type": "integer", "minimum": 0},
                "dpi": {"type": "number", "minimum": 18, "maximum": MAX_DPI}
            }), &[]),
        }),
        json!({
            "name": "newpub_new",
            "description": "Start a new publication: from a built-in template (`template`: see query \
                builtin_templates, e.g. \"newsletter\", \"flyer\", \"bulletin\", \"booklet\") or blank with a page \
                size (`width`/`height`, default US Letter portrait; `facing` for a two-page spread layout).",
            "inputSchema": obj(json!({
                "template": {"type": "string"},
                "width": {"type": ["string", "number"]},
                "height": {"type": ["string", "number"]},
                "facing": {"type": "boolean"},
                "pages": {"type": "integer", "minimum": 1}
            }), &[]),
        }),
        json!({
            "name": "newpub_open",
            "description": "Open a publication: a newpub file (.newspub / .npub), a Microsoft Publisher .pub file \
                (imported as a new, unsaved publication) or a predecessor NewsPub .newspub file.",
            "inputSchema": obj(json!({"path": {"type": "string"}}), &["path"]),
        }),
        json!({
            "name": "newpub_save",
            "description": "Save the publication as .newspub. Without `path`, saves to the file it was opened from.",
            "inputSchema": obj(json!({"path": {"type": "string"}}), &[]),
        }),
        json!({
            "name": "newpub_export_pdf",
            "description": "Export a PDF. `standard` may be \"pdf_x4\" or \"pdf_ua1\"; `pages` is a list of 0-based \
                page indexes (default all); `booklet` imposes a saddle-stitched booklet; `bleed` and `crop_marks` \
                add print marks. Other exports (PNG, HTML, EPUB, XPS, Pack and Go) are actions: see newpub_reference.",
            "inputSchema": obj(json!({
                "path": {"type": "string"},
                "standard": {"type": "string", "enum": ["pdf_x4", "pdf_ua1"]},
                "pages": {"type": "array", "items": {"type": "integer", "minimum": 0}},
                "booklet": {"type": "boolean"},
                "bleed": {"type": "boolean"},
                "crop_marks": {"type": "boolean"}
            }), &["path"]),
        }),
    ]
}

/// Names of every tool, in `tools()` order.
pub fn tool_names() -> Vec<String> {
    tools().iter().filter_map(|t| t.get("name").and_then(|n| n.as_str()).map(str::to_string)).collect()
}

/// Runs one tool. Errors come back as results with `is_error`, never as JSON-RPC errors, so the agent can read
/// and act on them.
pub fn call_tool(host: &mut dyn Host, name: &str, args: &Value) -> ToolResult {
    match call(host, name, args) {
        Ok(r) => r,
        Err(e) => ToolResult::error(format!("{name}: {e:#}")),
    }
}

fn call(host: &mut dyn Host, name: &str, args: &Value) -> Result<ToolResult> {
    let args = match args {
        Value::Object(m) => m.clone(),
        Value::Null => Map::new(),
        other => bail!("arguments must be an object, got {other}"),
    };
    match name {
        "newpub_reference" => Ok(reference(&args)),
        "newpub_status" => Ok(ToolResult::data("Publication status", status(host.session()))),
        "newpub_action" => {
            let name = str_arg(&args, "action")?;
            let a = to_action(name, args.get("args").unwrap_or(&Value::Null))?;
            let out = host.session().run(&a).map_err(|e| anyhow!("{e}\n(newpub_reference search: \"{name}\")"))?;
            host.after_actions(&format!("Agent: {name}"));
            let created: Vec<Id> = out.created;
            let summary = if created.is_empty() {
                format!("{name}: done")
            } else {
                format!(
                    "{name}: done, created {}",
                    created.iter().map(|i| i.0.to_string()).collect::<Vec<_>>().join(", ")
                )
            };
            Ok(ToolResult::data(summary, json!({"ok": true, "created": created})))
        }
        "newpub_actions" => actions(host, &args),
        "newpub_query" => {
            let name = str_arg(&args, "query")?;
            let mut q = match args.get("args") {
                Some(Value::Object(m)) => m.clone(),
                Some(Value::Null) | None => Map::new(),
                Some(other) => bail!("args must be an object, got {other}"),
            };
            q.insert("q".into(), Value::String(name.into()));
            let q: Query = serde_json::from_value(Value::Object(q))
                .map_err(|e| anyhow!("{e}\n(newpub_reference search: \"{name}\")"))?;
            let v = host.session().query(&q).map_err(|e| anyhow!("{e}"))?;
            Ok(ToolResult::data(format!("{name}:"), v))
        }
        "newpub_render_page" => render_page(host.session(), &args),
        "newpub_new" => {
            let a = match args.get("template").and_then(|t| t.as_str()) {
                Some(id) => Action::Session(SessionAction::NewFromBuiltin { id: id.to_string() }),
                None => {
                    let mut m = Map::new();
                    m.insert("cmd".into(), "new_document".into());
                    m.insert("width".into(), args.get("width").cloned().unwrap_or_else(|| "8.5in".into()));
                    m.insert("height".into(), args.get("height").cloned().unwrap_or_else(|| "11in".into()));
                    for k in ["facing", "pages"] {
                        if let Some(v) = args.get(k) {
                            m.insert(k.into(), v.clone());
                        }
                    }
                    serde_json::from_value(Value::Object(m))?
                }
            };
            host.session().run(&a).map_err(|e| anyhow!("{e}"))?;
            host.after_actions("Agent: new publication");
            Ok(ToolResult::data("New publication", status(host.session())))
        }
        "newpub_open" => {
            let path = str_arg(&args, "path")?.to_string();
            let a = if path.to_ascii_lowercase().ends_with(".pub") {
                SessionAction::ImportPub { path: path.clone() }
            } else {
                SessionAction::Open { path: path.clone() }
            };
            host.session().run(&a.into()).map_err(|e| anyhow!("{e}"))?;
            host.after_actions(&format!("Agent: opened {path}"));
            Ok(ToolResult::data(format!("Opened {path}"), status(host.session())))
        }
        "newpub_save" => {
            let s = host.session();
            let path = match args.get("path").and_then(|p| p.as_str()) {
                Some(p) => p.to_string(),
                None => s
                    .path
                    .as_ref()
                    .map(|p| p.to_string_lossy().to_string())
                    .ok_or_else(|| anyhow!("the publication has no file yet: give a path"))?,
            };
            s.run(&SessionAction::Save { path: path.clone() }.into()).map_err(|e| anyhow!("{e}"))?;
            host.after_actions(&format!("Agent: saved {path}"));
            Ok(ToolResult::data(format!("Saved {path}"), json!({"ok": true, "path": path})))
        }
        "newpub_export_pdf" => {
            let path = str_arg(&args, "path")?.to_string();
            let mut options = Map::new();
            if let Some(s) = args.get("standard") {
                options.insert("standard".into(), s.clone());
            }
            if let Some(p) = args.get("pages") {
                options.insert("pages".into(), p.clone());
            }
            if args.get("booklet").and_then(|b| b.as_bool()).unwrap_or(false) {
                options.insert("imposition".into(), "booklet".into());
            }
            for k in ["bleed", "crop_marks"] {
                if let Some(v) = args.get(k) {
                    options.insert(k.into(), v.clone());
                }
            }
            let a: Action =
                serde_json::from_value(json!({"cmd": "export_pdf", "path": path, "options": Value::Object(options)}))?;
            host.session().run(&a).map_err(|e| anyhow!("{e}"))?;
            host.after_actions(&format!("Agent: exported {path}"));
            Ok(ToolResult::data(format!("Exported {path}"), json!({"ok": true, "path": path})))
        }
        other => bail!("unknown tool {other}; the tools are {}", tool_names().join(", ")),
    }
}

fn str_arg<'a>(args: &'a Map<String, Value>, key: &str) -> Result<&'a str> {
    args.get(key).and_then(|v| v.as_str()).ok_or_else(|| anyhow!("`{key}` (a string) is required"))
}

/// An action from its `cmd` name and fields, as journeys build them.
pub fn to_action(name: &str, args: &Value) -> Result<Action> {
    let mut obj = match args {
        Value::Object(m) => m.clone(),
        Value::Null => Map::new(),
        other => bail!("args of {name} must be an object, got {other}"),
    };
    obj.insert("cmd".into(), Value::String(name.into()));
    serde_json::from_value(Value::Object(obj)).map_err(|e| anyhow!("{e}\n(newpub_reference search: \"{name}\")"))
}

fn actions(host: &mut dyn Host, args: &Map<String, Value>) -> Result<ToolResult> {
    let list =
        args.get("actions").and_then(|a| a.as_array()).ok_or_else(|| anyhow!("`actions` (a list) is required"))?;
    let group = args.get("undo_group").and_then(|g| g.as_bool()).unwrap_or(true);
    // Parse everything first: a typo in step 3 should not run steps 1 and 2.
    let parsed: Vec<(String, Action)> = list
        .iter()
        .enumerate()
        .map(|(i, item)| {
            let name = item
                .get("action")
                .and_then(|a| a.as_str())
                .ok_or_else(|| anyhow!("actions[{i}] needs an \"action\" name"))?;
            Ok((name.to_string(), to_action(name, item.get("args").unwrap_or(&Value::Null))?))
        })
        .collect::<Result<_>>()?;
    let s = host.session();
    if group {
        s.run(&SessionAction::BeginGroup.into()).map_err(|e| anyhow!("{e}"))?;
    }
    let mut results = Vec::new();
    let mut failure = None;
    for (i, (name, a)) in parsed.iter().enumerate() {
        match s.run(a) {
            Ok(out) => results.push(json!({"action": name, "created": out.created})),
            Err(e) => {
                failure = Some(format!("actions[{i}] {name}: {e}"));
                break;
            }
        }
    }
    if group {
        s.run(&SessionAction::EndGroup.into()).map_err(|e| anyhow!("{e}"))?;
    }
    host.after_actions(&format!("Agent: {} actions", results.len()));
    let value = json!({"ok": failure.is_none(), "ran": results.len(), "results": results, "error": failure});
    match failure {
        Some(f) => Ok(ToolResult {
            content: vec![json!({"type": "text", "text": format!(
                "{f}\n{} of {} actions ran before the failure{}; the result is:\n{}",
                results.len(), parsed.len(),
                if group && !results.is_empty() { " (undo reverts them as one step)" } else { "" },
                pretty(&value))})],
            structured: Some(value),
            is_error: true,
        }),
        None => Ok(ToolResult::data(format!("{} actions done", results.len()), value)),
    }
}

fn render_page(s: &mut Session, args: &Map<String, Value>) -> Result<ToolResult> {
    let page = args.get("page").and_then(|p| p.as_u64()).unwrap_or(0) as usize;
    let dpi = args.get("dpi").and_then(|d| d.as_f64()).unwrap_or(72.0).clamp(18.0, MAX_DPI);
    let n = s.doc().pages.len();
    if page >= n {
        bail!("page {page} does not exist: the publication has {n} page(s), numbered from 0");
    }
    let pm = s.render_page(page, dpi).map_err(|e| anyhow!("{e}"))?;
    let (w, h) = (pm.width(), pm.height());
    let png = pm.encode_png().map_err(|e| anyhow!("{e}"))?;
    let data = base64::engine::general_purpose::STANDARD.encode(&png);
    Ok(ToolResult {
        content: vec![
            json!({"type": "text", "text": format!("Page {page} ({} of {n}) at {dpi} dpi: {w}x{h} px", page + 1)}),
            json!({"type": "image", "data": data, "mimeType": "image/png"}),
        ],
        structured: Some(json!({"page": page, "dpi": dpi, "width": w, "height": h})),
        is_error: false,
    })
}

fn reference(args: &Map<String, Value>) -> ToolResult {
    let entries: Vec<&str> = REFERENCE.split("\n### ").collect();
    let (intro, rest) = entries.split_first().unwrap_or((&"", &[]));
    if args.get("names_only").and_then(|n| n.as_bool()).unwrap_or(false) {
        let mut out = String::new();
        for e in rest {
            if let Some(name) = e.split('`').nth(1) {
                out.push_str(name);
                out.push('\n');
            }
        }
        return ToolResult::text(out);
    }
    match args.get("search").and_then(|s| s.as_str()).map(|s| s.trim().to_lowercase()).filter(|s| !s.is_empty()) {
        Some(needle) => {
            let hits: Vec<String> = rest
                .iter()
                .filter(|e| e.to_lowercase().contains(&needle))
                .map(|e| format!("### {}", e.trim_end()))
                .collect();
            if hits.is_empty() {
                ToolResult::text(format!(
                    "Nothing in the reference mentions {needle:?}. Try newpub_reference with names_only."
                ))
            } else {
                ToolResult::text(format!("{} entries mention {needle:?}:\n\n{}", hits.len(), hits.join("\n\n")))
            }
        }
        None => ToolResult::text(format!("{intro}\n### {}", rest.join("\n### "))),
    }
}

/// A compact picture of the session for the agent.
pub fn status(s: &mut Session) -> Value {
    let layout = s.layout();
    let doc = s.doc();
    let kind_name = |k: &ObjectKind| match k {
        ObjectKind::Text(_) => "text",
        ObjectKind::Shape(_) => "shape",
        ObjectKind::Image(_) => "picture",
        ObjectKind::Table(_) => "table",
        ObjectKind::Group { .. } => "group",
        ObjectKind::WordArt(_) => "wordart",
    };
    let mut overflowing = Vec::new();
    let pages: Vec<Value> = doc
        .pages
        .iter()
        .enumerate()
        .map(|(i, p)| {
            let objects: Vec<Value> = p
                .objects
                .iter()
                .filter_map(|id| doc.objects.get(id))
                .map(|o| {
                    let mut v = json!({
                        "id": o.id,
                        "kind": kind_name(&o.kind),
                        "name": o.name,
                        "rect": {"x": o.rect.x, "y": o.rect.y, "w": o.rect.w, "h": o.rect.h},
                    });
                    if let ObjectKind::Text(t) = &o.kind {
                        if let Ok(st) = doc.story(t.story) {
                            let preview: String =
                                st.text.chars().take(60).map(|c| if c == '\n' { ' ' } else { c }).collect();
                            v["story"] = json!(t.story);
                            v["text"] = json!(preview);
                            v["chars"] = json!(st.text.chars().count());
                            if st.frames.len() > 1 {
                                v["chain"] = json!(st.frames);
                            }
                        }
                        if layout.frames.get(&o.id).is_some_and(|f| f.overflow) {
                            v["overflow"] = json!(true);
                            overflowing.push(o.id);
                        }
                    }
                    if o.locked {
                        v["locked"] = json!(true);
                    }
                    v
                })
                .collect();
            json!({"page": i, "master": p.master, "objects": objects})
        })
        .collect();
    let mut warnings = Vec::new();
    if !overflowing.is_empty() {
        warnings.push(format!(
            "text overflows in text box(es) {}: link them to another box, autoflow, or shrink the text",
            overflowing.iter().map(|i| i.0.to_string()).collect::<Vec<_>>().join(", ")
        ));
    }
    let path = s.path.as_ref().map(|p| p.to_string_lossy().to_string());
    let dirty = s.dirty;
    let (can_undo, can_redo) = (s.can_undo(), s.can_redo());
    let doc = s.doc();
    let (w, h) = (doc.setup.width.0, doc.setup.height.0);
    let page_count = doc.pages.len();
    if let Ok(Value::Array(missing)) = s.query(&Query::MissingFonts)
        && !missing.is_empty()
    {
        warnings.push(format!("missing fonts (drawn with stand-ins): {}", pretty(&Value::Array(missing))));
    }
    json!({
        "path": path,
        "dirty": dirty,
        "can_undo": can_undo,
        "can_redo": can_redo,
        "page_size_pt": {"width": w, "height": h},
        "page_count": page_count,
        "pages": pages,
        "warnings": warnings,
    })
}

// ---- JSON-RPC / MCP -----------------------------------------------------------------------------------------

/// Handles one JSON-RPC message. Notifications get `None`; requests get a response object.
pub fn handle(host: &mut dyn Host, msg: &Value) -> Option<Value> {
    let id = msg.get("id").cloned();
    let method = msg.get("method").and_then(|m| m.as_str()).unwrap_or("");
    let params = msg.get("params").cloned().unwrap_or(Value::Null);
    let reply = |result: Value| Some(json!({"jsonrpc": "2.0", "id": id, "result": result}));
    let error = |code: i64, message: String| {
        Some(json!({"jsonrpc": "2.0", "id": id, "error": {"code": code, "message": message}}))
    };
    match method {
        "initialize" => {
            let asked = params.get("protocolVersion").and_then(|v| v.as_str()).unwrap_or("");
            let version = PROTOCOL_VERSIONS.iter().find(|v| **v == asked).unwrap_or(&PROTOCOL_VERSIONS[0]);
            reply(json!({
                "protocolVersion": version,
                "capabilities": {"tools": {"listChanged": false}, "resources": {"subscribe": false, "listChanged": false}},
                "serverInfo": {"name": SERVER_NAME, "version": SERVER_VERSION},
                "instructions": INSTRUCTIONS,
            }))
        }
        "ping" => reply(json!({})),
        "tools/list" => reply(json!({"tools": tools()})),
        "tools/call" => {
            let name = params.get("name").and_then(|n| n.as_str()).unwrap_or("");
            let args = params.get("arguments").cloned().unwrap_or(Value::Null);
            reply(call_tool(host, name, &args).to_json())
        }
        "resources/list" => reply(json!({"resources": [{
            "uri": REFERENCE_URI, "name": "newpub action and query reference", "mimeType": "text/markdown",
            "description": "Every action and query newpub_action and newpub_query accept, with their fields."
        }]})),
        "resources/read" => match params.get("uri").and_then(|u| u.as_str()) {
            Some(REFERENCE_URI) => reply(json!({"contents": [{
                "uri": REFERENCE_URI, "mimeType": "text/markdown", "text": REFERENCE}]})),
            Some(other) => error(-32602, format!("unknown resource {other}")),
            None => error(-32602, "resources/read needs a uri".into()),
        },
        "prompts/list" => reply(json!({"prompts": []})),
        m if m.starts_with("notifications/") => None,
        "" => error(-32600, "message has no method".into()),
        other if id.is_none() => {
            // An unknown notification: nothing to answer.
            let _ = other;
            None
        }
        other => error(-32601, format!("method not found: {other}")),
    }
}

/// What MCP clients show their model about this server.
const INSTRUCTIONS: &str = "newpub is a desktop publishing program (Microsoft Publisher parity) for newsletters, \
bulletins, flyers and booklets. Start with newpub_status (or newpub_new / newpub_open). Make changes with \
newpub_action and newpub_actions using the names from newpub_reference (search it by topic: \"text frame\", \
\"link\", \"picture\", \"table\", \"style\", \"export\"). Ask questions with newpub_query (story_text, frame_lines, \
overflow, page_objects, accessibility_check, find, ...). Look at the result with newpub_render_page. Geometry is \
in points (72 per inch) from the page's top-left corner; lengths also accept strings such as \"2in\" or \"50mm\"; \
pages are numbered from 0. Every action is one undo step: newpub_action \"undo\" reverts it. Save with \
newpub_save and export with newpub_export_pdf.";

/// Serves MCP on stdin/stdout until stdin closes. Diagnostics go to stderr; stdout carries only JSON-RPC.
pub fn serve_stdio(host: &mut dyn Host) -> Result<()> {
    let stdin = std::io::stdin();
    let mut out = std::io::stdout().lock();
    for line in stdin.lock().lines() {
        let line = line?;
        if line.trim().is_empty() {
            continue;
        }
        let reply = match serde_json::from_str::<Value>(&line) {
            Ok(msg) => handle(host, &msg),
            Err(e) => Some(
                json!({"jsonrpc": "2.0", "id": null, "error": {"code": -32700, "message": format!("parse error: {e}")}}),
            ),
        };
        if let Some(r) = reply {
            writeln!(out, "{r}")?;
            out.flush()?;
        }
    }
    Ok(())
}

/// What wakes the host's thread when a request is queued (the app sets it to `Context::request_repaint`).
pub type Waker = Arc<Mutex<Option<Box<dyn Fn() + Send>>>>;

/// A stdio MCP connection for a host that lives on another thread (the app's UI thread): requests arrive on
/// `requests`, replies go back through `reply`. `wake` is called whenever a request is queued.
pub struct Link {
    pub requests: mpsc::Receiver<Value>,
    out: Arc<Mutex<std::io::Stdout>>,
}

impl Link {
    pub fn reply(&self, v: &Value) {
        if let Ok(mut out) = self.out.lock() {
            let _ = writeln!(out, "{v}");
            let _ = out.flush();
        }
    }

    /// Answers every queued request through `host`.
    pub fn pump(&self, host: &mut dyn Host) -> usize {
        let mut n = 0;
        while let Ok(msg) = self.requests.try_recv() {
            n += 1;
            if let Some(r) = handle(host, &msg) {
                self.reply(&r);
            }
        }
        n
    }
}

/// Starts the stdin reader thread of a [`Link`]. `wake` runs on that thread after each queued message.
pub fn stdio_link(wake: Waker) -> Link {
    let (tx, rx) = mpsc::channel();
    let out = Arc::new(Mutex::new(std::io::stdout()));
    let errors = out.clone();
    std::thread::Builder::new()
        .name("newpub-agent-stdin".into())
        .spawn(move || {
            let stdin = std::io::stdin();
            for line in stdin.lock().lines() {
                let Ok(line) = line else { break };
                if line.trim().is_empty() {
                    continue;
                }
                match serde_json::from_str::<Value>(&line) {
                    Ok(msg) => {
                        if tx.send(msg).is_err() {
                            break;
                        }
                    }
                    Err(e) => {
                        if let Ok(mut o) = errors.lock() {
                            let _ = writeln!(o, "{}", json!({"jsonrpc": "2.0", "id": null, "error": {"code": -32700, "message": format!("parse error: {e}")}}));
                            let _ = o.flush();
                        }
                    }
                }
                if let Ok(w) = wake.lock()
                    && let Some(f) = w.as_ref()
                {
                    f();
                }
            }
        })
        .expect("spawn the agent stdin thread");
    Link { requests: rx, out }
}
