[package]
name = "newpub-io-pdf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
newpub-render.workspace = true
serde.workspace = true
newpub-core.workspace = true
newpub-layout.workspace = true
krilla.workspace = true
lopdf.workspace = true
thiserror.workspace = true
usvg.workspace = true
krilla-svg.workspace = true
serde_json.workspace = true
